webtalk_init -webtalk_dir D:/Users/hamze/Dropbox/Academic/Courses/Bilkent TA_Digital_Design_CS223/Fall 2016/Labs/Projects_Vivado2016.3_Basys3/keyboard_matrix/keyboard_matrix.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 02 16:47:27 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "28a35149cb025164b9e325bcefaf26e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5a6f6ed9458d447d9b19c7722e16089d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) 2957U @ 1.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1396 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "60001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "26.46_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15420_KB" -context "xsim\\usage"
webtalk_transmit -clientid 425321454 -regid "" -xml D:/Users/hamze/Dropbox/Academic/Courses/Bilkent TA_Digital_Design_CS223/Fall 2016/Labs/Projects_Vivado2016.3_Basys3/keyboard_matrix/keyboard_matrix.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Users/hamze/Dropbox/Academic/Courses/Bilkent TA_Digital_Design_CS223/Fall 2016/Labs/Projects_Vivado2016.3_Basys3/keyboard_matrix/keyboard_matrix.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Users/hamze/Dropbox/Academic/Courses/Bilkent TA_Digital_Design_CS223/Fall 2016/Labs/Projects_Vivado2016.3_Basys3/keyboard_matrix/keyboard_matrix.sim/sim_1/behav/xsim.dir/testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
