# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS.001/Desktop/lab4/lab4.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS.001/Desktop/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv D:/Users/TEMP.PCLABS.001/Desktop/lab4/lab4.srcs/sources_1/new/DFlipFlop.sv
read_xdc D:/Users/TEMP.PCLABS.001/Desktop/lab4/Basys3.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS.001/Desktop/lab4/Basys3.xdc]

synth_design -top TwoBitUpCounter_Clk -part xc7a35tcpg236-1
write_checkpoint -noxdef TwoBitUpCounter_Clk.dcp
catch { report_utilization -file TwoBitUpCounter_Clk_utilization_synth.rpt -pb TwoBitUpCounter_Clk_utilization_synth.pb }
