# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS.000/Desktop/decoder/decoder.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS.000/Desktop/decoder/decoder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv D:/Users/TEMP.PCLABS.000/Desktop/decoder/decoder.srcs/sources_1/new/D2to4_decoder.sv
read_xdc D:/Users/TEMP.PCLABS.000/Desktop/Basys3.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS.000/Desktop/Basys3.xdc]

synth_design -top D2to4_decoder -part xc7a35tcpg236-1
write_checkpoint -noxdef D2to4_decoder.dcp
catch { report_utilization -file D2to4_decoder_utilization_synth.rpt -pb D2to4_decoder_utilization_synth.pb }
